# -*- coding: utf-8 -*-
"""
Created on 2023-04-19 15:30:01
---------
@summary:
---------
@author: SL-COM-254
"""

from feapder import Item


class JincongxinItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i jincongxin
    """

    __table_name__ = "jincongxin"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.manufacturers = None
        self.price = None
        self.rank = None
        self.sales = None
        self.vehicle_type = None
